In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [5]:
df = pd.read_csv('height-weight.csv')

In [6]:
df.head()

   Weight  Height
0      45     120
1      58     135
2      48     123
3      60     145
4      70     160

In [7]:
# Scatter plot
plt.scatter(df['Weight'] , df['Height'])
plt.xlabel("Weight")
plt.ylabel("Height")

Text(0, 0.5, 'Height')

In [8]:
# Correlation
df.corr()

          Weight    Height
Weight  1.000000  0.931142
Height  0.931142  1.000000

In [9]:
# Seaborn for visulaization
import seaborn as sns
sns.pairplot(df)

In [10]:

df.head()

   Weight  Height
0      45     120
1      58     135
2      48     123
3      60     145
4      70     160

In [11]:
# Independent and dependent feature
X = df[['Weight']] # independent feature should be data frame or 2 dimensional array
y = df['Height'] # this variable can be in series or 1D Array

In [12]:
# Train , Test
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.25 , random_state = 42)

In [13]:
X_train.shape

(17, 1)

In [14]:
# Standardization
from sklearn.preprocessing import StandardScaler

In [15]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)

In [16]:
X_test = scaler.transform(X_test)

In [17]:
# Apply Simple Linear Regression
from sklearn.linear_model import LinearRegression

In [18]:
regression = LinearRegression(n_jobs = -1)

In [19]:
regression.fit(X_train , y_train)

LinearRegression(n_jobs=-1)

In [20]:
regression

LinearRegression(n_jobs=-1)

In [21]:
print("Coefficient or slope : " , regression.coef_)
print("Intercept : " , regression.intercept_)

Coefficient or slope :  [17.2982057]
Intercept :  156.47058823529412

In [22]:
# plot Training data best fit line
plt.scatter(X_train , y_train)
plt.plot(X_train , regression.predict(X_train))

Prediction on Test Data
1. predicted height output = Intercept + coef_(weight)
2. y_pred_test = 156.420 + 17.29(X_test)

In [23]:
# Prediction for test_data
y_pred = regression.predict(X_test)

In [24]:
# Performance Metrics
from sklearn.metrics import mean_absolute_error , mean_squared_error

In [25]:
mse = mean_squared_error(y_test , y_pred)
mae = mean_absolute_error(y_test , y_pred)
rmse = np.sqrt(mse)
print(mse)
print(mae)
print(rmse)

114.84069295228699
9.665125886795005
10.716374991212605

R Square

Formula

R^2 = 1 - SSR/SST

R^2 = coefficient of determination SSR = sum of squares of residuals SST = total sum of squares

In [26]:
from sklearn.metrics import r2_score

In [27]:
score = r2_score(y_test , y_pred)

Adjusted R2=1-[(1-R2)^ * (n - 1) / (n - k - 1) ]

where:

R2: The R2 of the model n: The number of observations k: The number of predictor variables

In [28]:
# Display Adjusted R - squared
1 - (1 - score) * (len(y_test) - 1) / (len(y_test) - X_test.shape[1] - 1)

0.6701033397476595

In [29]:
# OLS Linear Regression
import statsmodels.api as sm

In [30]:
model = sm.OLS(y_train , X_train).fit()

In [31]:
prediction = model.predict(X_test)
print(prediction)

[  5.79440897   5.79440897 -28.78711691  23.60913442  -7.82861638
  34.08838469]

In [32]:
print(model.summary())

                                 OLS Regression Results
=======================================================================================
Dep. Variable:                 Height   R-squared (uncentered):                   0.012
Model:                            OLS   Adj. R-squared (uncentered):             -0.050
Method:                 Least Squares   F-statistic:                             0.1953
Date:                Sat, 30 May 2026   Prob (F-statistic):                       0.664
Time:                        21:39:56   Log-Likelihood:                         -110.03
No. Observations:                  17   AIC:                                      222.1
Df Residuals:                      16   BIC:                                      222.9
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            17.2982     39.138      0.442      0.664     -65.671     100.267
==============================================================================
Omnibus:                        0.135   Durbin-Watson:                   0.002
Prob(Omnibus):                  0.935   Jarque-Bera (JB):                0.203
Skew:                          -0.166   Prob(JB):                        0.904
Kurtosis:                       2.581   Cond. No.                         1.00
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.

/opt/anaconda3/lib/python3.13/site-packages/scipy/stats/_axis_nan_policy.py:430: UserWarning: `kurtosistest` p-value may be inaccurate with fewer than 20 observations; only n=17 observations were given.
  return hypotest_fun_in(*args, **kwds)

In [33]:
# Prediction for new data
regression.predict(scaler.transform([[72]]))

/opt/anaconda3/lib/python3.13/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

array([155.97744705])